#!/usr/bin/env python3
"""
Boomi Process Generator (Spec-Driven)
Reads any platform-agnostic migration spec, generates Boomi component XML
(process + connections + operations), writes to active-development/, and
optionally pushes each component to the Boomi platform.

Usage:
    python generators/generate_boomi.py migration-specs/my-project.json
    python generators/generate_boomi.py migration-specs/my-project.json --dry-run
    python generators/generate_boomi.py migration-specs/my-project.json --folder-id Rjo4NTYzMTMw

Required: BOOMI_TARGET_FOLDER in .env (auto-detected from active-development/ XML if present)
"""

import argparse
import glob
import json
import os
import re
import subprocess
import sys
import uuid
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
from textwrap import dedent


# ─── Constants ────────────────────────────────────────────────────────────────

DB_CONNECTOR   = "officialboomi-X3979C-dbv2da-prod"
REST_CONNECTOR = "officialboomi-X3979C-rest-prod"
WSS_CONNECTOR  = "wss"

DB_OP_TYPES = {
    "db_select": ("GET",    "QUERY"),
    "db_insert": ("CREATE", "CREATE"),
    "db_update": ("UPDATE", "UPDATE"),
    "db_delete": ("DELETE", "DELETE"),
}

WSS_HTTP_TO_OP = {
    "GET":    "QUERY",
    "POST":   "CREATE",
    "PUT":    "UPDATE",
    "PATCH":  "UPDATE",
    "DELETE": "DELETE",
}

# Canvas layout: shapes spaced 225px apart horizontally
X_START = 48.0
X_STEP  = 225.0
Y_ROW   = 46.0


# ─── Utilities ────────────────────────────────────────────────────────────────

def new_id():
    return str(uuid.uuid4())


def safe_name(s):
    return re.sub(r"[^\w]", "_", s).strip("_")


def xml_escape(s):
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def detect_folder_id():
    """
    Extract folderId from the first XML component found in active-development/.
    Falls back to None if not found.
    """
    pattern = os.path.join("active-development", "**", "*.xml")
    for fpath in glob.glob(pattern, recursive=True):
        try:
            tree = ET.parse(fpath)
            root = tree.getroot()
            ns = {"bns": "http://api.platform.boomi.com/"}
            fid = root.get("folderId")
            if fid:
                return fid
        except Exception:
            continue
    return None


def find_skill_path():
    """Locate boomi-integration skill scripts directory."""
    p = os.environ.get("BOOMI_SKILL_PATH")
    if p and os.path.isdir(p):
        return os.path.join(p, "scripts")
    candidates = [
        os.path.expanduser("~/.claude/plugins/cache/boomi-companion/bc-integration/*/skills/boomi-integration"),
        os.path.expanduser("~/.claude/plugins/cache/boomi-companion/*/skills/boomi-integration"),
    ]
    for pattern in candidates:
        matches = glob.glob(pattern)
        if matches:
            return os.path.join(sorted(matches)[-1], "scripts")
    return None


# ─── XML Component Templates ──────────────────────────────────────────────────

COMPONENT_WRAPPER = """\
<?xml version="1.0" encoding="UTF-8"?>
<bns:Component xmlns:bns="http://api.platform.boomi.com/"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               componentId="{component_id}" name="{name}"
               type="{comp_type}"{sub_type_attr}
               folderId="{folder_id}">
  <bns:encryptedValues>{encrypted_values}
  </bns:encryptedValues>
  <bns:description>generated by boomi-migration-agent</bns:description><bns:object>
{inner_xml}
  </bns:object>{overrides}
</bns:Component>
"""


def wrap_component(component_id, name, comp_type, inner_xml,
                   folder_id, sub_type=None, encrypted_values="",
                   overrides=""):
    sub_type_attr = f'\n               subType="{sub_type}"' if sub_type else ""
    ov = "\n  <bns:processOverrides/>" if comp_type == "process" else ""
    return COMPONENT_WRAPPER.format(
        component_id=component_id,
        name=name,
        comp_type=comp_type,
        sub_type_attr=sub_type_attr,
        folder_id=folder_id,
        encrypted_values=encrypted_values,
        inner_xml=inner_xml,
        overrides=ov,
    )


# ─── WSS Operation ────────────────────────────────────────────────────────────

def gen_wss_operation(component_id, name, folder_id, http_method, object_name):
    op_type = WSS_HTTP_TO_OP.get(http_method.upper(), "QUERY")
    inner = dedent(f"""\
    <Operation>
      <Archiving directory="" enabled="false"/>
      <Configuration>
        <WebServicesServerListenAction
          inputType="none"
          objectName="{object_name}"
          operationType="{op_type}"
          outputType="singledata"
          responseContentType="application/json"/>
      </Configuration>
      <Tracking><TrackedFields/></Tracking>
      <Caching/>
    </Operation>""")
    return wrap_component(component_id, name, "connector-action", inner,
                          folder_id, sub_type=WSS_CONNECTOR)


# ─── DB Connection ────────────────────────────────────────────────────────────

def gen_db_connection(component_id, name, folder_id, jdbc_url="jdbc:postgresql://localhost:5432/db",
                      username="${db.user}", password="${db.password}"):
    inner = dedent(f"""\
    <GenericConnectionConfig>
      <field id="url" type="string" value="{xml_escape(jdbc_url)}"/>
      <field id="className" type="string" value="org.postgresql.Driver"/>
      <field id="username" type="string" value="{xml_escape(username)}"/>
      <field id="password" type="password" value="{xml_escape(password)}"/>
      <field id="CustomProperties" type="customproperties">
        <customProperties/>
      </field>
      <field id="schemaName" type="string" value=""/>
      <field id="connectTimeOut" type="integer"/>
      <field id="readTimeOut" type="integer"/>
      <field id="enablePooling" type="boolean" value="false"/>
      <field id="maximumConnections" type="integer" value=""/>
      <field id="minimumConnections" type="integer" value=""/>
      <field id="maximumIdleTime" type="integer" value=""/>
      <field id="whenExhaustedAction" type="string" value=""/>
      <field id="maximumWaitTime" type="integer" value=""/>
      <field id="testOnBorrow" type="boolean" value=""/>
      <field id="testOnReturn" type="boolean" value=""/>
      <field id="testWhileIdle" type="boolean" value=""/>
      <field id="validationQuery" type="string" value=""/>
    </GenericConnectionConfig>""")
    encrypted = '\n    <bns:encryptedValue isSet="true" path="//GenericConnectionConfig/field[@type=\'password\']"/>'
    return wrap_component(component_id, name, "connector-settings", inner,
                          folder_id, sub_type=DB_CONNECTOR,
                          encrypted_values=encrypted)


# ─── DB Operation ─────────────────────────────────────────────────────────────

def gen_db_operation(component_id, name, folder_id, step):
    stype = step.get("type", "db_select")
    custom_op, _ = DB_OP_TYPES.get(stype, ("GET", "QUERY"))
    table = step.get("table", "table")
    sql = xml_escape(step.get("sql", f"SELECT * FROM {table}"))

    inner = dedent(f"""\
    <Operation returnApplicationErrors="true" trackResponse="false">
      <Archiving directory="" enabled="false"/>
      <Configuration>
        <GenericOperationConfig
          customOperationType="{custom_op}"
          objectTypeId="{table}"
          operationType="EXECUTE"
          requestProfileType="json"
          responseProfileType="json">
          <field id="GetType" type="string" value="Standard Get"/>
          <field id="INClause" type="boolean" value="false"/>
          <field id="query" type="string" value="{sql}"/>
          <field id="linkElement" type="string" value=""/>
          <field id="maxRows" type="integer"/>
          <field id="maxFieldSize" type="integer"/>
          <field id="batchCount" type="integer"/>
          <field id="fetchSize" type="integer"/>
          <Options>
            <QueryOptions>
              <Fields>
                <ConnectorObject name="{table}">
                  <FieldList/>
                </ConnectorObject>
              </Fields>
              <Inputs/>
            </QueryOptions>
          </Options>
        </GenericOperationConfig>
      </Configuration>
      <Tracking><TrackedFields/></Tracking>
      <Caching/>
    </Operation>""")
    return wrap_component(component_id, name, "connector-action", inner,
                          folder_id, sub_type=DB_CONNECTOR)


# ─── REST Connection ──────────────────────────────────────────────────────────

def gen_rest_connection(component_id, name, folder_id, base_url="https://api.example.com"):
    inner = dedent(f"""\
    <GenericConnectionConfig>
      <field id="url" type="string" value="{xml_escape(base_url)}"/>
      <field id="authenticationType" type="string" value="None"/>
      <field id="connectTimeout" type="integer"/>
      <field id="readTimeout" type="integer"/>
      <field id="maxConnections" type="integer"/>
      <field id="maxConnectionsPerRoute" type="integer"/>
      <field id="addtlAuthContext"/>
    </GenericConnectionConfig>""")
    return wrap_component(component_id, name, "connector-settings", inner,
                          folder_id, sub_type=REST_CONNECTOR)


# ─── REST Operation ───────────────────────────────────────────────────────────

def gen_rest_operation(component_id, name, folder_id, step):
    method = (step.get("http_method") or "GET").upper()
    url_path = xml_escape(step.get("url") or step.get("path") or "/endpoint")
    inner = dedent(f"""\
    <Operation returnApplicationErrors="true" trackResponse="false">
      <Archiving directory="" enabled="false"/>
      <Configuration>
        <GenericOperationConfig
          customOperationType="{method}"
          operationType="EXECUTE"
          requestProfileType="json"
          responseProfileType="json">
          <field id="httpMethod" type="string" value="{method}"/>
          <field id="resourcePath" type="string" value="{url_path}"/>
          <field id="contentType" type="string" value="application/json"/>
          <field id="acceptType" type="string" value="application/json"/>
        </GenericOperationConfig>
      </Configuration>
      <Tracking><TrackedFields/></Tracking>
      <Caching/>
    </Operation>""")
    return wrap_component(component_id, name, "connector-action", inner,
                          folder_id, sub_type=REST_CONNECTOR)


# ─── Process XML Builder ──────────────────────────────────────────────────────

class ProcessShapeBuilder:
    """
    Builds the sequence of <shape> elements for a Boomi process.
    Shapes are laid out left-to-right with X_STEP spacing.
    """

    def __init__(self, flow, wss_op_id, db_conn_id, db_op_ids,
                 rest_conn_id, rest_op_ids):
        self.flow = flow
        self.wss_op_id = wss_op_id
        self.db_conn_id = db_conn_id
        self.db_op_ids = db_op_ids        # {sequence -> op_id}
        self.rest_conn_id = rest_conn_id
        self.rest_op_ids = rest_op_ids    # {sequence -> op_id}
        self.notes = []
        self._shape_num = 0
        self._shapes = []

    def build(self):
        self._shape_num = 0
        self._shapes = []

        # Start shape
        trigger = self.flow.get("trigger", {})
        self._add_trigger(trigger)

        # Step shapes
        steps = self.flow.get("steps", [])
        for step in steps:
            self._add_step(step)

        # Terminal shape (return or stop)
        has_return = any(s.get("type") in ("return_response", "set_payload")
                         for s in steps)
        if not has_return:
            self._add_return()

        # Wire dragpoints
        shapes_xml = self._build_shapes_xml()
        return shapes_xml, self.notes

    # ── Private ───────────────────────────────────────────────────────────────

    def _next(self):
        self._shape_num += 1
        x = X_START + (self._shape_num - 1) * X_STEP
        return f"shape{self._shape_num}", x

    def _add_trigger(self, trigger):
        name, x = self._next()
        ttype = trigger.get("type", "")
        if ttype == "http_listener":
            self._shapes.append(("start_wss", name, x, trigger))
        elif ttype == "scheduler":
            self._shapes.append(("start_schedule", name, x, trigger))
        else:
            self._shapes.append(("start_no_data", name, x, trigger))
            self.notes.append(f"Trigger '{ttype}' mapped to No Data start — reconfigure in Boomi")

    def _add_step(self, step):
        name, x = self._next()
        stype = step.get("type", "")
        if stype in DB_OP_TYPES:
            self._shapes.append(("db", name, x, step))
        elif stype == "http_request":
            self._shapes.append(("rest", name, x, step))
        elif stype == "transform":
            self._shapes.append(("map", name, x, step))
            self.notes.append(f"Map step '{step.get('label','')}' — wire source/target profiles in Boomi Map editor")
        elif stype == "custom_script":
            self._shapes.append(("groovy", name, x, step))
        elif stype == "choice_router":
            self._shapes.append(("decision", name, x, step))
            self.notes.append(f"Conditional step '{step.get('label','')}' — configure decision logic in Boomi")
        elif stype in ("return_response", "set_payload"):
            self._shapes.append(("return", name, x, step))
        elif stype == "set_variable":
            self._shapes.append(("setprops", name, x, step))
        elif stype == "subprocess_call":
            self._shapes.append(("processcall", name, x, step))
            self.notes.append(f"Subprocess '{step.get('label','')}' — link to target sub-process in Boomi")
        elif stype in ("sequence", "logger", "branch", "loop", "connector_action"):
            self._shapes.append(("message", name, x, step))
            self.notes.append(f"Step '{stype}' ({step.get('label','')}) — review and reconfigure in Boomi")
        else:
            self._shapes.append(("message", name, x, step))
            self.notes.append(f"Step '{stype}' not auto-mapped — review in Boomi")

    def _add_return(self):
        name, x = self._next()
        self._shapes.append(("return", name, x, {}))

    def _build_shapes_xml(self):
        lines = []
        for i, entry in enumerate(self._shapes):
            shape_type = entry[0]
            shape_name = entry[1]
            x = entry[2]
            data = entry[3]

            next_name = self._shapes[i + 1][1] if i + 1 < len(self._shapes) else None
            dp_xml = self._dragpoint(shape_name, x, next_name)
            label = xml_escape(data.get("label", "")) if isinstance(data, dict) else ""
            seq = data.get("sequence") if isinstance(data, dict) else None

            if shape_type == "start_wss":
                lines.append(self._shape_start_wss(shape_name, x, dp_xml))
            elif shape_type in ("start_schedule", "start_no_data"):
                lines.append(self._shape_start_no_data(shape_name, x, dp_xml))
            elif shape_type == "db":
                op_id = self.db_op_ids.get(seq, "")
                lines.append(self._shape_db(shape_name, x, label, op_id, dp_xml))
            elif shape_type == "rest":
                op_id = self.rest_op_ids.get(seq, "")
                lines.append(self._shape_rest(shape_name, x, label, op_id, dp_xml))
            elif shape_type == "map":
                lines.append(self._shape_map(shape_name, x, label, dp_xml))
            elif shape_type == "groovy":
                lines.append(self._shape_groovy(shape_name, x, label, dp_xml))
            elif shape_type == "decision":
                lines.append(self._shape_decision(shape_name, x, label, dp_xml))
            elif shape_type == "setprops":
                lines.append(self._shape_setprops(shape_name, x, label, data, dp_xml))
            elif shape_type == "processcall":
                lines.append(self._shape_processcall(shape_name, x, label, dp_xml))
            elif shape_type == "message":
                lines.append(self._shape_message(shape_name, x, label, dp_xml))
            elif shape_type == "return":
                lines.append(self._shape_return(shape_name, x))

        return "\n".join(lines)

    def _dragpoint(self, shape_name, x, next_name):
        if not next_name:
            return "          <dragpoints/>"
        dp_x = x + X_STEP
        dp_y = Y_ROW + 10
        return (f'          <dragpoints>\n'
                f'            <dragpoint name="{shape_name}.dragpoint1" toShape="{next_name}"'
                f' x="{dp_x}" y="{dp_y}"/>\n'
                f'          </dragpoints>')

    def _shape_start_wss(self, name, x, dp):
        return (f'        <shape image="start" name="{name}" shapetype="start" userlabel="" x="{x}" y="{Y_ROW}">\n'
                f'          <configuration>\n'
                f'            <connectoraction actionType="Listen" allowDynamicCredentials="NONE"\n'
                f'              connectorType="{WSS_CONNECTOR}" hideSettings="true"\n'
                f'              operationId="{self.wss_op_id}">\n'
                f'              <parameters/>\n'
                f'              <dynamicProperties/>\n'
                f'            </connectoraction>\n'
                f'          </configuration>\n'
                f'{dp}\n'
                f'        </shape>')

    def _shape_start_no_data(self, name, x, dp):
        return (f'        <shape image="start" name="{name}" shapetype="start" userlabel="" x="{x}" y="{Y_ROW}">\n'
                f'          <configuration>\n'
                f'            <nodata/>\n'
                f'          </configuration>\n'
                f'{dp}\n'
                f'        </shape>')

    def _shape_db(self, name, x, label, op_id, dp):
        return (f'        <shape image="connectoraction_icon" name="{name}" shapetype="connectoraction"\n'
                f'          userlabel="{label}" x="{x}" y="{Y_ROW}">\n'
                f'          <configuration>\n'
                f'            <connectoraction actionType="GET" allowDynamicCredentials="NONE"\n'
                f'              connectionId="{self.db_conn_id}"\n'
                f'              connectorType="{DB_CONNECTOR}"\n'
                f'              hideSettings="false"\n'
                f'              operationId="{op_id}">\n'
                f'              <parameters/>\n'
                f'              <dynamicProperties/>\n'
                f'            </connectoraction>\n'
                f'          </configuration>\n'
                f'{dp}\n'
                f'        </shape>')

    def _shape_rest(self, name, x, label, op_id, dp):
        return (f'        <shape image="connectoraction_icon" name="{name}" shapetype="connectoraction"\n'
                f'          userlabel="{label}" x="{x}" y="{Y_ROW}">\n'
                f'          <configuration>\n'
                f'            <connectoraction actionType="GET" allowDynamicCredentials="NONE"\n'
                f'              connectionId="{self.rest_conn_id}"\n'
                f'              connectorType="{REST_CONNECTOR}"\n'
                f'              hideSettings="false"\n'
                f'              operationId="{op_id}">\n'
                f'              <parameters/>\n'
                f'              <dynamicProperties/>\n'
                f'            </connectoraction>\n'
                f'          </configuration>\n'
                f'{dp}\n'
                f'        </shape>')

    def _shape_map(self, name, x, label, dp):
        map_id = new_id()
        return (f'        <shape image="map_icon" name="{name}" shapetype="map"\n'
                f'          userlabel="{label}" x="{x}" y="{Y_ROW}">\n'
                f'          <configuration>\n'
                f'            <map mapId="{map_id}"/>\n'
                f'          </configuration>\n'
                f'{dp}\n'
                f'        </shape>')

    def _shape_groovy(self, name, x, label, dp):
        return (f'        <shape image="dataprocess_icon" name="{name}" shapetype="dataprocess"\n'
                f'          userlabel="{label}" x="{x}" y="{Y_ROW}">\n'
                f'          <configuration>\n'
                f'            <dataprocess>\n'
                f'              <step index="1" key="1" name="Custom Scripting" processtype="12">\n'
                f'                <dataprocessscript language="groovy2" useCache="true">\n'
                f'                  <script>// TODO: implement custom logic for {xml_escape(label)}</script>\n'
                f'                </dataprocessscript>\n'
                f'              </step>\n'
                f'            </dataprocess>\n'
                f'          </configuration>\n'
                f'{dp}\n'
                f'        </shape>')

    def _shape_decision(self, name, x, label, dp):
        return (f'        <shape image="decision_icon" name="{name}" shapetype="decision"\n'
                f'          userlabel="{label}" x="{x}" y="{Y_ROW}">\n'
                f'          <configuration>\n'
                f'            <decision comparator="EQUAL" valueType="STATIC_VALUE">\n'
                f'              <firstOperand type="DYNAMIC_DOCUMENT_PROPERTY" name="condition"/>\n'
                f'              <secondOperand type="STATIC" value="true"/>\n'
                f'            </decision>\n'
                f'          </configuration>\n'
                f'{dp}\n'
                f'        </shape>')

    def _shape_setprops(self, name, x, label, step, dp):
        content = xml_escape(str(step.get("static_content", "")))[:200]
        return (f'        <shape image="setproperties_icon" name="{name}" shapetype="setproperties"\n'
                f'          userlabel="{label}" x="{x}" y="{Y_ROW}">\n'
                f'          <configuration>\n'
                f'            <setproperties>\n'
                f'              <setproperty propertyName="content" propertyType="DYNAMIC" valueType="STATIC_VALUE">\n'
                f'                <value><![CDATA[{content}]]></value>\n'
                f'              </setproperty>\n'
                f'            </setproperties>\n'
                f'          </configuration>\n'
                f'{dp}\n'
                f'        </shape>')

    def _shape_processcall(self, name, x, label, dp):
        return (f'        <shape image="processcall_icon" name="{name}" shapetype="processcall"\n'
                f'          userlabel="{label}" x="{x}" y="{Y_ROW}">\n'
                f'          <configuration>\n'
                f'            <processcall processId="" waitForComplete="true"/>\n'
                f'          </configuration>\n'
                f'{dp}\n'
                f'        </shape>')

    def _shape_message(self, name, x, label, dp):
        return (f'        <shape image="message_icon" name="{name}" shapetype="message"\n'
                f'          userlabel="{label}" x="{x}" y="{Y_ROW}">\n'
                f'          <configuration>\n'
                f'            <message combined="false">\n'
                f'              <msgTxt><!-- TODO: configure message for {xml_escape(label)} --></msgTxt>\n'
                f'              <msgParameters/>\n'
                f'            </message>\n'
                f'          </configuration>\n'
                f'{dp}\n'
                f'        </shape>')

    def _shape_return(self, name, x):
        return (f'        <shape image="return_icon" name="{name}" shapetype="returndocuments"\n'
                f'          userlabel="" x="{x}" y="{Y_ROW}">\n'
                f'          <configuration>\n'
                f'            <returndocuments/>\n'
                f'          </configuration>\n'
                f'          <dragpoints/>\n'
                f'        </shape>')


def gen_process(component_id, name, folder_id, shapes_xml):
    inner = dedent(f"""\
    <process allowSimultaneous="true" enableUserLog="false" processLogOnErrorOnly="false"
             purgeDataImmediately="false" updateRunDates="false" workload="general">
      <shapes>
{shapes_xml}
      </shapes>
    </process>""")
    return wrap_component(component_id, name, "process", inner, folder_id)


# ─── Flow Generator ───────────────────────────────────────────────────────────

class BoomiFlowGenerator:
    """
    For one canonical flow spec, generates all required Boomi component XMLs.
    Returns a list of (comp_type, subdir, filename, xml_content, notes).
    """

    def __init__(self, flow, spec, folder_id, project_prefix):
        self.flow = flow
        self.spec = spec
        self.folder_id = folder_id
        self.prefix = project_prefix
        self.all_notes = []

    def generate(self):
        """Returns list of (subdir, filename_stem, xml_str) and notes."""
        components = []
        trigger = self.flow.get("trigger", {})
        steps = self.flow.get("steps", [])

        flow_name = self.flow.get("name", "Flow")
        if not flow_name.upper().startswith("MIG_"):
            flow_name = f"MIG_{flow_name}"

        # ── Assign all IDs upfront ────────────────────────────────────────
        process_id  = new_id()
        wss_op_id   = new_id() if trigger.get("type") == "http_listener" else None
        db_conn_id  = None
        rest_conn_id = None
        db_op_ids   = {}   # seq -> id
        rest_op_ids = {}   # seq -> id

        db_steps   = [s for s in steps if s.get("type") in DB_OP_TYPES]
        rest_steps = [s for s in steps if s.get("type") == "http_request"]

        if db_steps:
            db_conn_id = new_id()
        if rest_steps:
            rest_conn_id = new_id()

        for s in db_steps:
            db_op_ids[s["sequence"]] = new_id()
        for s in rest_steps:
            rest_op_ids[s["sequence"]] = new_id()

        # ── WSS operation ─────────────────────────────────────────────────
        if wss_op_id:
            http_method = trigger.get("http_method", "GET").upper()
            path = trigger.get("path", "/endpoint")
            object_name = path.strip("/").split("/")[0] or "resource"
            wss_name = f"{flow_name}_WSSOperation"
            components.append((
                "connector-action", wss_name,
                gen_wss_operation(wss_op_id, wss_name, self.folder_id,
                                  http_method, object_name)
            ))

        # ── DB connection ─────────────────────────────────────────────────
        if db_conn_id:
            jdbc_url = self._infer_jdbc()
            conn_name = f"MIG_{self.prefix}_DB_Connection"
            components.append((
                "connector-settings", conn_name,
                gen_db_connection(db_conn_id, conn_name, self.folder_id, jdbc_url)
            ))
            for s in db_steps:
                op_name = f"{flow_name}_{safe_name(s.get('label', s['type']))}_Operation"
                components.append((
                    "connector-action", op_name,
                    gen_db_operation(db_op_ids[s["sequence"]], op_name,
                                     self.folder_id, s)
                ))

        # ── REST connection ───────────────────────────────────────────────
        if rest_conn_id:
            base_url = rest_steps[0].get("url", "https://api.example.com")
            conn_name = f"MIG_{self.prefix}_REST_Connection"
            components.append((
                "connector-settings", conn_name,
                gen_rest_connection(rest_conn_id, conn_name, self.folder_id, base_url)
            ))
            for s in rest_steps:
                op_name = f"{flow_name}_{safe_name(s.get('label', s['type']))}_Operation"
                components.append((
                    "connector-action", op_name,
                    gen_rest_operation(rest_op_ids[s["sequence"]], op_name,
                                       self.folder_id, s)
                ))

        # ── Process ───────────────────────────────────────────────────────
        builder = ProcessShapeBuilder(self.flow, wss_op_id, db_conn_id,
                                      db_op_ids, rest_conn_id, rest_op_ids)
        shapes_xml, notes = builder.build()
        self.all_notes.extend(notes)

        components.append((
            "process", flow_name,
            gen_process(process_id, flow_name, self.folder_id, shapes_xml)
        ))

        return components, self.all_notes

    def _infer_jdbc(self):
        """Try to extract JDBC URL from spec connections or return a placeholder."""
        conns = self.spec.get("connections", {})
        for k, v in conns.items():
            url = v.get("jdbc_url") or v.get("url")
            if url:
                return url
        return "jdbc:postgresql://localhost:5432/db"


# ─── File writer & pusher ─────────────────────────────────────────────────────

SUBDIR_MAP = {
    "process":           "process",
    "connector-action":  "connector-action",
    "connector-settings": "connector-settings",
}


def write_component(subdir, name, xml_str, output_dir):
    target_dir = os.path.join(output_dir, subdir)
    os.makedirs(target_dir, exist_ok=True)
    fpath = os.path.join(target_dir, f"{name}.xml")
    with open(fpath, "w", encoding="utf-8") as f:
        f.write(xml_str)
    return fpath


def push_component(fpath, scripts_dir):
    """
    Create a new component in Boomi via boomi-component-create.sh.
    Success is determined by whether the componentId was written back to the
    XML file, not just the script exit code (jq parse errors in the script's
    response parsing can cause non-zero exit even when creation succeeded).
    """
    create_script = os.path.join(scripts_dir, "boomi-component-create.sh")
    if not os.path.isfile(create_script):
        print(f"  ERROR: create script not found at {create_script}", file=sys.stderr)
        return False

    # Record componentId before the call so we can detect if it changed
    id_before = _read_component_id_from_xml(fpath)

    subprocess.run(["bash", create_script, fpath], capture_output=False, text=True)

    # Success = script updated the file with a platform-assigned componentId,
    # OR the component already existed (id_before was already set)
    id_after = _read_component_id_from_xml(fpath)
    return bool(id_after)


def _read_component_id_from_xml(fpath):
    """Extract componentId attribute from a Boomi component XML file."""
    try:
        tree = ET.parse(fpath)
        return tree.getroot().get("componentId", "")
    except Exception:
        return ""


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Generate Boomi processes from a migration spec.")
    parser.add_argument("spec", nargs="?", default="migration-specs/boomi-customer-api.json")
    parser.add_argument("--folder-id", default=None,
                        help="Boomi folder ID for generated components (auto-detected if omitted)")
    parser.add_argument("--project", default=None,
                        help="Project prefix for shared component names (default: spec project_name)")
    parser.add_argument("--output-dir", default="active-development",
                        help="Directory to write component XML files (default: active-development)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Write XML files locally without pushing to Boomi")
    args = parser.parse_args()

    if not os.path.isfile(args.spec):
        print(f"ERROR: Spec not found: {args.spec}", file=sys.stderr)
        sys.exit(1)

    with open(args.spec, encoding="utf-8") as f:
        spec = json.load(f)

    project_name = args.project or spec.get("project_name", "Migration")
    flows = spec.get("integrations", [])

    # Detect folder ID
    folder_id = args.folder_id or detect_folder_id()
    if not folder_id:
        print("ERROR: Could not detect folderId. Pass --folder-id <id> or ensure "
              "active-development/ contains existing Boomi XML.", file=sys.stderr)
        sys.exit(1)

    print(f"Boomi Generator")
    print(f"  Source  : {spec.get('source_system')}")
    print(f"  Project : {project_name}")
    print(f"  Flows   : {len(flows)}")
    print(f"  Folder  : {folder_id}")
    print(f"  Output  : {args.output_dir}")
    print(f"  Dry run : {args.dry_run}")

    # Locate skill scripts (needed for push)
    scripts_dir = None
    if not args.dry_run:
        scripts_dir = find_skill_path()
        if not scripts_dir:
            print("ERROR: Could not find boomi-integration skill scripts. "
                  "Set BOOMI_SKILL_PATH in .env or use --dry-run.", file=sys.stderr)
            sys.exit(1)
        print(f"  Skill   : {scripts_dir}")

    all_results = []
    all_notes = []

    for flow in flows:
        flow_name = flow.get("name", "Flow")
        print(f"\nGenerating flow: {flow_name}")

        generator = BoomiFlowGenerator(flow, spec, folder_id, safe_name(project_name))
        components, notes = generator.generate()
        all_notes.extend([(flow_name, n) for n in notes])

        for (subdir, comp_name, xml_str) in components:
            fpath = write_component(subdir, comp_name, xml_str, args.output_dir)
            status = "written"
            print(f"  [{subdir}] {comp_name}")

            if not args.dry_run:
                ok = push_component(fpath, scripts_dir)
                status = "pushed" if ok else "push_failed"
                print(f"    -> {status}")

            all_results.append({"flow": flow_name, "component": comp_name,
                                 "file": fpath, "status": status})

    # Output summary
    output_path = args.spec.replace(".json", "_boomi_output.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump({
            "project": project_name,
            "folder_id": folder_id,
            "components": all_results,
            "manual_review": [{"flow": f, "note": n} for f, n in all_notes],
        }, f, indent=2)

    total = len(all_results)
    pushed = sum(1 for r in all_results if r["status"] == "pushed")
    written = sum(1 for r in all_results if r["status"] == "written")

    print(f"\n{'=' * 50}")
    if args.dry_run:
        print(f"Done (dry run). {written} component files written to {args.output_dir}/")
    else:
        print(f"Done. {pushed}/{total} components pushed to Boomi.")
    print(f"Output: {output_path}")

    if all_notes:
        print(f"\nManual review ({len(all_notes)} items):")
        for flow_name, note in all_notes:
            print(f"  [{flow_name}] {note[:100]}")


if __name__ == "__main__":
    main()
