#!/usr/bin/env python3
"""
Push script: GLD FundingEngine — processFundingRequest (v3)
Generated by: initiate_migration/Instruction_Workato.md 6-step workflow
Skill used:   Workato/Companion/SKILL.md (workato-integration)
Source ref:   WebMethods/MD/GLDFundingEngine_WMToWorkato.md

Target folder: migrAIte_Training/webMethodsMigration (ID: 32159265)
Account:       manish@techstonellc.com

Recipe structure (per WMToWorkato.md prompts 1–15):
  TRIGGER (Prompt 1-3): workato_service/receive_request "GLD FundingEngine — processFundingRequest"
    Flat schema: id, customerName, customerID, sourceName, sourceSubCategory, salesRepName, payments (JSON string)

  [1] try (Prompt 4)
    [2] each: payment_loop source=trigger.payments.parse_json (Prompt 5)
      [3] if: type == "Check" (Prompt 6)
        [4] HTTP POST → invokeGetUniquePayee      (Prompt 7  — rows 5.2 rows 1-11)
        [5] if payeeKey is_empty:                 (Prompt 8  — IF/ELSE rule: 5.2 row 12)
          [6] HTTP POST → invokeAddNewPayee
        [7] HTTP POST → invokeCreateCheckRequest  (Prompt 9  — 5.2 rows 12-17)
      [8] elsif: type == "ACH" (Prompt 10)
        [9] Oracle execute_stored_procedure →     (Prompt 11 — Oracle rule: 5.3 rows 1-11)
              GLD_ACH.INSERTPAYMENT (11 params)
      [10] else: Default/Wire (Prompt 12)
        [11] Logger → "Default path"
      rescue (last in each.block, Prompt 13):
        [12] HTTP POST → GLDMessageLog:LogXMLRequest
    catch (last in try.block, Prompt 14):
      [13] HTTP POST → GLDMessageLog:LogXMLRequest
  [14] workato_service/send_reply → PAYMENTS_PROCESSED (Prompt 15)

Connections (wire in Workato GUI after push):
  GLDFundingEngine_CheckWriter_Connection  → steps 4, 6, 7 (HTTP — base URL from SME)
  MIG_WM_GLD_Oracle_Connection (19657520) → step 9      (Oracle ACH insertPayment)
  GLDFundingEngine_MessageLog_Connection   → steps 12, 13 (HTTP — base URL from SME)

Placeholders to configure in GUI:
  - [CHECKWRITER_BASE_URL] — obtain from SME (GLDExpressGateway base URL)
  - [MESSAGELOG_BASE_URL]  — obtain from SME (GLDMessageLog endpoint)
  - GLD_ACH.INSERTPAYMENT  — confirm exact schema.procedure name with SME
  - error.message pills in rescue + catch steps — wire manually in GUI

Workato-integration skill rules applied (all 15):
  Rule 1:  Trigger schema flattened — payments passed as JSON string
  Rule 2:  toggleCfg: {} on every action step
  Rule 3:  dynamicPickListSelection: {} on every action step
  Rule 4:  parameters_schema: "" on callable trigger
  Rule 5:  rescue is last sibling in each.block
  Rule 6:  catch is last sibling in try.block
  Rule 7:  keyword: "elsif" (flat sibling, not nested)
  Rule 8:  folder creation uses flat JSON (not wrapped)
  Rule 9:  recipe code and config are JSON strings in POST payload
  Rule 10: not applicable (new recipe — no GET before PUT needed)
  Rule 11: uuid on every step
  Rule 12: current_item path element for loop pills
  Rule 13: account_id is integer (19657520) for Oracle; null for http/logger/workato_service
  Rule 14: keyword "each" used (confirmed working)
  Rule 15: extended_output_schema set on trigger
"""

import json
import os
import sys
import uuid
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
RECIPE_NAME = "GLD FundingEngine — processFundingRequest"
FOLDER_ID   = "31835141"   # MigrAIte_Training (top-level; subfolder 32159265 may not exist)
DRY_RUN     = "--dry-run" in sys.argv

# Oracle connection ID (MIG_WM_GLD_Oracle_Connection, already in account)
ORACLE_CONN_ID = 19657520

# Placeholder URLs — replace with real values from SME
CHECKWRITER_BASE_URL = "https://webmethods-gateway.keybank.internal"
MESSAGELOG_BASE_URL  = "https://webmethods-log.keybank.internal"

# ── Auth ──────────────────────────────────────────────────────────────────────
def load_env():
    """Walk ancestor directories to find .env (Rule: credential access via file parsing)."""
    env_path = Path(__file__).resolve().parent
    for _ in range(6):
        candidate = env_path / ".env"
        if candidate.exists():
            for line in candidate.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))
            return
        env_path = env_path.parent
    raise RuntimeError(".env not found in ancestor directories")

load_env()
TOKEN    = os.environ.get("WORKATO_API_TOKEN", "")
# Use hardcoded base URL (same as v2 script that successfully pushed 74461729)
# WORKATO_BASE_URL env var may have trailing slash — hardcode avoids double-slash URLs.
BASE_URL = "https://www.workato.com/api"
if not TOKEN:
    sys.exit("ERROR: WORKATO_API_TOKEN not set in .env")

# ── HTTP helper ───────────────────────────────────────────────────────────────
import urllib.request
import urllib.error

def api(method, path, body=None):
    url  = BASE_URL + path   # path must start with "/" e.g. "/recipes"
    data = json.dumps(body).encode() if body else None
    req  = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {TOKEN}")
    req.add_header("Content-Type",  "application/json")
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        body_text = e.read().decode(errors="replace")
        sys.exit(f"HTTP {e.code} {method} {path}:\n{body_text[:1000]}")

# ── UUID helper ───────────────────────────────────────────────────────────────
def uid():
    """Every step MUST have a unique UUID (Rule 11)."""
    return str(uuid.uuid4())

# ── Datapill helpers (Rule 12 — current_item for loop items) ──────────────────
def _pill_json(provider, line, *path_parts):
    path = []
    for p in path_parts:
        if p == "*":
            path.append({"path_element_type": "current_item"})
        else:
            path.append(p)
    return json.dumps({
        "pill_type": "output",
        "provider":  provider,
        "line":      line,
        "path":      path,
    }).replace('"', '\\"')

def dp(provider, line, *path_parts):
    """Return a Workato datapill template string."""
    return "#{_dp('" + _pill_json(provider, line, *path_parts) + "')}"

def raw_dp(provider, line, *path_parts):
    """Return raw _dp(...) expression (for use inside #{} formulas)."""
    return "_dp('" + _pill_json(provider, line, *path_parts) + "')"

# ── Step alias constants ───────────────────────────────────────────────────────
TRIG_AS        = uid()[:8]
GET_PAYEE_AS   = uid()[:8]
ADD_PAYEE_AS   = uid()[:8]
CREATE_CHK_AS  = uid()[:8]
ORA_ACH_AS     = uid()[:8]
LOG_DEF_AS     = uid()[:8]
RESCUE_LOG_AS  = uid()[:8]
CATCH_LOG_AS   = uid()[:8]
REPLY_AS       = uid()[:8]

# ── Datapill accessors ─────────────────────────────────────────────────────────
# Trigger flat fields (Prompt 2 — Section 5.1)
def trig(field):
    return dp("workato_service", TRIG_AS, "request", field)

# Payment loop item fields (Section 5.2 / 5.3)
def pay(field):
    return dp("workato", "payment_loop", "*", field)

def http_out(alias, field):
    return dp("http", alias, field)

def raw_http(alias, field):
    return raw_dp("http", alias, field)

# ── PayeeInformation payload (Section 5.2 rows 1–11) ─────────────────────────
# Used by both invokeGetUniquePayee (Prompt 7) and invokeAddNewPayee (Prompt 8)
PAYEE_INFO = {
    "PayeeName":            pay("payee_name"),           # row 1
    "AddressLine1":         pay("payee_address1"),        # row 2
    "AddressLine2":         pay("payee_address2"),        # row 3
    "City":                 pay("payee_city"),             # row 4
    "State":                pay("payee_state_province"),   # row 5
    "PostalCode":           pay("payee_zip"),              # row 6
    "PhoneNumber":          pay("payee_phone"),            # row 7
    "FaxNumber":            pay("payee_fax"),              # row 8
    "ContactName":          pay("payee_contactName"),      # row 9
    "ContactPhoneNumber":   pay("payee_contactPhone"),     # row 10
    "Country":              "USA",                         # row 11 — static
}

# ── HTTP step builder (Rules 2, 3, 11) ────────────────────────────────────────
def http_post(num, title, alias, url, payload_dict):
    """Prompt 7 / 8 / 9 / 12 / 13 pattern — HTTP POST action."""
    return {
        "number":  num,
        "keyword": "action",
        "provider": "http",
        "name":    "post",
        "as":      alias,
        "title":   title,
        "uuid":    uid(),
        "dynamicPickListSelection": {},   # Rule 3
        "toggleCfg": {},                   # Rule 2
        "input": {
            "url":          url,
            "content_type": "application/json",
            "payload":      json.dumps(payload_dict),
        },
    }

# ── Oracle SP builder (Prompt 11 — Oracle rule: Section 5.3) ──────────────────
def oracle_sp(num, alias, proc_name, params, title=None):
    """
    Prompt 11 — Create a new Workato Step with Oracle as connection.
    Rules 2, 3, 11, 13 applied.
    """
    inp = {"procedure_name": proc_name}
    inp.update(params)
    step = {
        "number":  num,
        "keyword": "action",
        "provider": "oracle",
        "name":    "execute_stored_procedure",
        "as":      alias,
        "uuid":    uid(),
        "dynamicPickListSelection": {"procedure_name": proc_name},  # Rule 3
        "toggleCfg": {},                                              # Rule 2
        "input":   inp,
    }
    if title:
        step["title"] = title
    return step

# ── Prompt 7: HTTP POST → invokeGetUniquePayee ────────────────────────────────
step4_get_payee = http_post(
    4,
    "Check.1 — invokeGetUniquePayee (GLDExpressGateway CheckWriter, 11 payee fields)",
    GET_PAYEE_AS,
    CHECKWRITER_BASE_URL + "/GLDExpressGateway/CheckWriter/invokeGetUniquePayee",
    PAYEE_INFO,
)

# ── Prompt 8: If Else block — payeeKey OR addNewPayee (5.2 row 12 — IF/ELSE rule)
step6_add_payee = http_post(
    6,
    "Check.1b — invokeAddNewPayee (register new payee in CheckWriter)",
    ADD_PAYEE_AS,
    CHECKWRITER_BASE_URL + "/GLDExpressGateway/CheckWriter/invokeAddNewPayee",
    PAYEE_INFO,
)

step5_if_no_payee = {
    "number":  5,
    "keyword": "if",
    "title":   "Payee not found (payeeKey empty) — Add a new If Else block",
    "uuid":    uid(),
    "toggleCfg": {},   # Rule 2
    "input": {
        "type":    "compound",
        "operand": "and",
        "conditions": [{
            "operand": "is_empty",
            "lhs":     http_out(GET_PAYEE_AS, "payeeKey"),
            "uuid":    uid(),
        }],
    },
    "block": [step6_add_payee],
}

# ── Prompt 9: HTTP POST → invokeCreateCheckRequest (5.2 rows 12–17) ──────────
# Row 12 — PayeeKey: combined formula (presence || fallback)
PAYEE_KEY_FORMULA = (
    "#{" + raw_http(GET_PAYEE_AS, "payeeKey") +
    ".presence || " + raw_http(ADD_PAYEE_AS, "payeeKey") + "}"
)

step7_create_check = http_post(
    7,
    "Check.2 — invokeCreateCheckRequest (PayeeKey + 6 fields, 5.2 rows 12-17)",
    CREATE_CHK_AS,
    CHECKWRITER_BASE_URL + "/GLDExpressGateway/CheckWriter/invokeCreateCheckRequest",
    {
        "PayeeKey":    PAYEE_KEY_FORMULA,         # row 12 — combined formula from If Else
        "Notes":       pay("invoiceReference"),   # row 13
        "Comments":    pay("comment"),             # row 14
        "CheckAmount": pay("amount"),              # row 15
        "Memo":        pay("checkMemo"),           # row 16
        "LeaseNumber": trig("id"),                 # row 17 — applicationInfo.id
    },
)

# ── Prompt 6: if: type == "Check" ─────────────────────────────────────────────
step3_if_check = {
    "number":  3,
    "keyword": "if",
    "title":   "Prompt 6 — if payment.type == Check",
    "uuid":    uid(),
    "toggleCfg": {},   # Rule 2
    "input": {
        "type":    "compound",
        "operand": "and",
        "conditions": [{
            "operand": "equals",
            "lhs":     pay("type"),
            "rhs":     "Check",
            "uuid":    uid(),
        }],
    },
    "block": [step4_get_payee, step5_if_no_payee, step7_create_check],
}

# ── Prompt 11: Oracle execute_stored_procedure → insertPayment ────────────────
# Oracle rule applied: Section 5.3 — all 11 rows map to Oracle SP params
# "Create a new Workato Step with Oracle as connection"
step9_oracle_ach = oracle_sp(
    9,
    ORA_ACH_AS,
    "GLD_ACH.INSERTPAYMENT",   # placeholder — confirm exact schema.proc name with SME
    {
        "REQUESTOR_ID":   "1",               # row 1 — static REQUESTOR constant
        "APP_ID":         trig("id"),         # row 2 — applicationInfo.id
        "CUSTOMER_NAME":  trig("customerName"),  # row 3
        "CUSTOMER_ID":    trig("customerID"),    # row 4
        "SOURCE":         trig("sourceName"),    # row 5
        "AMOUNT":         pay("amount"),          # row 6
        "REFERENCE":      pay("invoiceReference"), # row 7
        "PAYEE_ID":       pay("payee_id"),         # row 8
        "PAYEE_NAME":     pay("payee_name"),        # row 9
        "ACCOUNT_NUMBER": pay("payee_accountNumber"), # row 10
        "ROUTING_NUMBER": pay("payee_routingNumber"),  # row 11
    },
    title="ACH — Oracle insertPayment (GLD_ACH.INSERTPAYMENT, 11 params from 5.3)",
)

# ── Prompt 10: elsif: type == "ACH" (Rule 7 — flat sibling, keyword: "elsif") ─
step8_elsif_ach = {
    "number":  8,
    "keyword": "elsif",   # Rule 7 — NOT "elseif", flat sibling to if
    "title":   "Prompt 10 — elsif payment.type == ACH",
    "uuid":    uid(),
    "toggleCfg": {},   # Rule 2
    "input": {
        "type":    "compound",
        "operand": "and",
        "conditions": [{
            "operand": "equals",
            "lhs":     pay("type"),
            "rhs":     "ACH",
            "uuid":    uid(),
        }],
    },
    "block": [step9_oracle_ach],
}

# ── Prompt 12: else — Default/Wire path (Logger) ──────────────────────────────
step11_log_default = {
    "number":   11,
    "keyword":  "action",
    "provider": "logger",
    "name":     "create_message",
    "as":       LOG_DEF_AS,
    "title":    "Prompt 12 — Default/Wire path — no external processor",
    "uuid":     uid(),
    "dynamicPickListSelection": {},   # Rule 3
    "toggleCfg": {},                   # Rule 2
    "input": {
        "message": (
            "Payment type Default/Wire — no external processor. "
            "Payment ID: " + pay("id") + " Type: " + pay("type")
        ),
        "level": "info",
    },
}

step10_else_default = {
    "number":  10,
    "keyword": "else",
    "title":   "Prompt 12 — else: Other/Wire/Default",
    "uuid":    uid(),
    "block":   [step11_log_default],
}

# ── Prompt 13: rescue (per-payment error log) — LAST in each.block (Rule 5) ───
step_rescue_log = http_post(
    12,
    "Prompt 13 — RESCUE: LogXMLRequest (GLDMessageLog, AppID=3, per-payment error)",
    RESCUE_LOG_AS,
    MESSAGELOG_BASE_URL + "/GLDMessageLog/LogXMLRequest",
    {
        "AppID":              "3",                # static
        "RequestIdentifier1": pay("id"),           # payment ID for traceability
        "ErrorMessage":       "[wire error.message pill in Workato GUI]",
    },
)

step_rescue = {
    "number":  14,
    "keyword": "rescue",   # last sibling in each.block (Rule 5)
    "uuid":    uid(),
    "block":   [step_rescue_log],
}

# ── each loop (Prompt 5) — payment_loop with parse_json ───────────────────────
# Source: trigger.payments.parse_json — applies .parse_json to the payments JSON string
_pay_pill = json.dumps({
    "pill_type": "output",
    "provider":  "workato_service",
    "line":      TRIG_AS,
    "path":      ["request", "payments"],
}).replace('"', '\\"')
PAYMENTS_SOURCE = "#{_dp('" + _pay_pill + "').parse_json}"

step2_each = {
    "number":  2,
    "keyword": "each",   # Rule 14 — "each" confirmed working
    "as":      "payment_loop",
    "title":   "Prompt 5 — repeat for each payment in payments.parse_json",
    "uuid":    uid(),
    "toggleCfg": {},    # Rule 2
    "input": {"source": PAYMENTS_SOURCE},
    "block": [
        step3_if_check,    # if Check
        step8_elsif_ach,   # elsif ACH   (Rule 7 — flat sibling)
        step10_else_default, # else Default
        step_rescue,       # LAST (Rule 5)
    ],
}

# ── Prompt 14: catch (outer error log) — LAST in try.block (Rule 6) ──────────
step_catch_log = http_post(
    13,
    "Prompt 14 — CATCH: LogXMLRequest (GLDMessageLog, AppID=3, outer error)",
    CATCH_LOG_AS,
    MESSAGELOG_BASE_URL + "/GLDMessageLog/LogXMLRequest",
    {
        "AppID":        "3",     # static
        "ErrorMessage": "[wire error.message pill in Workato GUI]",
    },
)

step_catch = {
    "number":  15,
    "keyword": "catch",   # last sibling in try.block (Rule 6)
    "uuid":    uid(),
    "input":   {"max_retry_count": "0", "retry_interval": "2"},
    "block":   [step_catch_log],
}

# ── Prompt 15: send_reply → PAYMENTS_PROCESSED ────────────────────────────────
step_send_reply = {
    "number":   16,
    "keyword":  "action",
    "provider": "workato_service",
    "name":     "send_reply",
    "as":       REPLY_AS,
    "uuid":     uid(),
    "dynamicPickListSelection": {},           # Rule 3
    "toggleCfg": {"reply.status": True},      # Rule 2
    "input": {
        "reply_type": "success",
        "reply": {"status": "PAYMENTS_PROCESSED"},
    },
    "extended_input_schema": [{
        "label": "Reply",
        "name":  "reply",
        "type":  "object",
        "properties": [{
            "control_type": "text",
            "label":        "Status",
            "name":         "status",
            "type":         "string",
            "optional":     False,
        }],
    }],
}

# ── Prompt 4: outer try block ─────────────────────────────────────────────────
step1_try = {
    "number":  1,
    "keyword": "try",
    "title":   "Prompt 4 — outer try block",
    "uuid":    uid(),
    "input":   {},
    "block":   [step2_each, step_send_reply, step_catch],  # catch LAST (Rule 6)
}

# ── Prompts 1-3: Trigger (callable recipe, flat schema — Rule 1) ──────────────
# Rule 1: ALL fields are scalar types. No nested objects or arrays.
# payments passed as JSON string — deserialized with .parse_json inside each loop.
req_schema = [
    {"name": "id",               "type": "string",  "optional": False, "control_type": "text",
     "label": "Application ID (1–100 chars) — maps to LeaseNumber in CheckWriter"},
    {"name": "customerName",     "type": "string",  "optional": False, "control_type": "text",
     "label": "Customer Name (max 100 chars)"},
    {"name": "customerID",       "type": "string",  "optional": False, "control_type": "text",
     "label": "Customer ID (integer 1–999999999999 as string)"},
    {"name": "sourceName",       "type": "string",  "optional": True,  "control_type": "text",
     "label": "Source Name — maps to SOURCE in Oracle insertPayment"},
    {"name": "sourceSubCategory","type": "string",  "optional": True,  "control_type": "text",
     "label": "Source Sub Category"},
    {"name": "salesRepName",     "type": "string",  "optional": True,  "control_type": "text",
     "label": "Sales Rep Name"},
    {"name": "payments",         "type": "string",  "optional": False, "control_type": "text",
     "label": (
         "Payments JSON array. Fields per item: id, type (Check|ACH|Other|Wire), amount, "
         "invoiceReference, comment, checkMemo, payee_id, payee_type, payee_name, "
         "payee_address1, payee_address2, payee_city, payee_state_province, payee_zip, "
         "payee_phone, payee_fax, payee_contactName, payee_contactPhone, "
         "payee_routingNumber, payee_accountNumber"
     )},
]

reply_schema = [
    {"name": "status", "type": "string", "optional": False, "control_type": "text",
     "label": "Processing status (PAYMENTS_PROCESSED)"},
]

# Rule 15: extended_output_schema must match request schema for GUI pills to work
extended_output = [
    {"name": f["name"], "type": f["type"], "label": f["label"]}
    for f in req_schema
]

trigger = {
    "number":   0,
    "keyword":  "trigger",
    "provider": "workato_service",
    "name":     "receive_request",
    "as":       TRIG_AS,
    "uuid":     uid(),
    "dynamicPickListSelection": {},   # Rule 3
    "toggleCfg": {},                   # Rule 2
    "parameters_schema": "",           # Rule 4 — required on callable trigger
    "input": {
        "service_name":        "FundingEngine",
        "request_schema_json": json.dumps(req_schema),
        "reply_schema_json":   json.dumps(reply_schema),
    },
    "extended_output_schema": extended_output,  # Rule 15
    "block": [step1_try],
}

# ── Config (Rule 13 — account_id is integer or null) ─────────────────────────
config = [
    # Prompt 1: workato_service (callable trigger + send_reply) — null
    {"keyword": "application", "provider": "workato_service",
     "account_id": None, "skip_validation": False},
    # Prompt 7/8/9: HTTP (CheckWriter + MessageLog) — null
    {"keyword": "application", "provider": "http",
     "account_id": None, "skip_validation": False},
    # Prompt 11: Oracle (insertPayment) — integer ID (Rule 13)
    {"keyword": "application", "provider": "oracle",
     "account_id": ORACLE_CONN_ID, "skip_validation": False},
    # Prompt 12: logger (Default path) — null
    {"keyword": "application", "provider": "logger",
     "account_id": None, "skip_validation": False},
]

# ── Payload (Rule 9: code and config MUST be JSON strings, not dicts) ─────────
payload = {
    "recipe": {
        "name":        RECIPE_NAME,
        "folder_id":   FOLDER_ID,   # string (Rule 9)
        "description": (
            "GLDFundingEngine20080714 → Workato. processFundingRequest. "
            "Generated by: initiate_migration/Instruction_Workato.md 6-step workflow. "
            "Skill: Workato/Companion/SKILL.md (workato-integration). "
            "Trigger: 7 flat fields (id, customerName, customerID, sourceName, "
            "sourceSubCategory, salesRepName, payments JSON string). "
            "Payment routing: Check (HTTP CheckWriter, 3 steps) | "
            "ACH (Oracle execute_stored_procedure GLD_ACH.INSERTPAYMENT, 11 params) | "
            "Default (Logger). Per-payment rescue + outer catch → GLDMessageLog. "
            "Source ref: WebMethods/MD/GLDFundingEngine_WMToWorkato.md (Prompts 1-15)."
        ),
        "code":   json.dumps(trigger),   # Rule 9 — JSON string
        "config": json.dumps(config),    # Rule 9 — JSON string
    }
}

# ── Push ───────────────────────────────────────────────────────────────────────
if DRY_RUN:
    print("=== DRY RUN — Recipe payload (code/config expanded for readability) ===\n")
    display = dict(payload["recipe"])
    display["code"]   = json.loads(display["code"])
    display["config"] = json.loads(display["config"])
    print(json.dumps({"recipe": display}, indent=2))
else:
    print(f"Pushing '{RECIPE_NAME}' to folder {FOLDER_ID} (migrAIte_Training/webMethodsMigration)...")
    result = api("POST", "/recipes", payload)
    recipe_id = result.get("id")
    if recipe_id:
        print(f"\nSUCCESS")
        print(f"  Recipe ID : {recipe_id}")
        print(f"  Name      : {result.get('name')}")
        print(f"  URL       : https://app.workato.com/recipes/{recipe_id}")
        print(f"\nRemaining GUI steps (per WMToWorkato.md):")
        print(f"  1. Connection — GLDFundingEngine_CheckWriter_Connection (HTTP):")
        print(f"     Wire to steps: invokeGetUniquePayee (4), invokeAddNewPayee (6), invokeCreateCheckRequest (7)")
        print(f"     URL: {CHECKWRITER_BASE_URL}  ← replace with real URL from SME")
        print(f"  2. Connection — MIG_WM_GLD_Oracle_Connection (Oracle, ID {ORACLE_CONN_ID}):")
        print(f"     Wire to step: insertPayment (9)")
        print(f"     Confirm SP name: GLD_ACH.INSERTPAYMENT (verify with SME)")
        print(f"  3. Connection — GLDFundingEngine_MessageLog_Connection (HTTP):")
        print(f"     Wire to steps: rescue LogXMLRequest (12), catch LogXMLRequest (13)")
        print(f"     URL: {MESSAGELOG_BASE_URL}  <- replace with real URL from SME")
        print(f"  4. Wire error.message pills in rescue (step 12) and catch (step 13) in GUI")
    else:
        print("Push returned 200 but no recipe ID. Response:")
        print(json.dumps(result, indent=2)[:600])
